# Generated by Django 2.1.5 on 2022-12-07 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blocco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set', models.IntegerField()),
                ('reps', models.IntegerField()),
                ('comment', models.TextField()),
                ('esercizio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allenamento.Esercizio')),
            ],
        ),
        migrations.CreateModel(
            name='Schedario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_scheda', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='blocco',
            name='nome_scheda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allenamento.Schedario'),
        ),
    ]
