# Generated by Django 2.1.5 on 2022-12-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0003_schedario_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Muscoli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('muscolo', models.CharField(max_length=20)),
            ],
        ),
    ]
