# Generated by Django 2.1.5 on 2022-12-08 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0004_muscoli'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedario',
            name='numero_mipiace',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
