# Generated by Django 2.1.5 on 2022-12-09 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0005_schedario_numero_mipiace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedario',
            name='numero_mipiace',
            field=models.IntegerField(default=0),
        ),
    ]
