# Generated by Django 2.1.5 on 2022-12-10 16:00

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0006_auto_20221209_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='esercizio',
            name='url',
            field=embed_video.fields.EmbedVideoField(default='https://www.youtube.com/watch?v=dGF1x14QNGA'),
            preserve_default=False,
        ),
    ]
