# Generated by Django 2.1.5 on 2022-12-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0008_schedario_pubblica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedario',
            name='pubblica',
            field=models.BooleanField(default='false'),
        ),
    ]
