# Generated by Django 2.1.5 on 2022-12-11 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0009_auto_20221211_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedario',
            name='pubblica',
            field=models.BooleanField(default=False),
        ),
    ]
