# Generated by Django 2.1.5 on 2022-12-11 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0010_auto_20221211_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedario',
            name='pubblica',
        ),
    ]
