# Generated by Django 2.1.5 on 2022-12-12 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0012_schedario_pubblica'),
    ]

    operations = [
        migrations.AddField(
            model_name='esercizio',
            name='muscoli',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allenamento.Muscoli'),
            preserve_default=False,
        ),
    ]
