# Generated by Django 2.1.5 on 2022-12-12 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0013_esercizio_muscoli'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='esercizio',
            name='muscoli',
        ),
        migrations.AddField(
            model_name='muscoli',
            name='esercizio_correlato',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allenamento.Esercizio'),
            preserve_default=False,
        ),
    ]
