# Generated by Django 2.1.5 on 2022-12-12 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0014_auto_20221212_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocco',
            name='zavorra',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
