# Generated by Django 2.1.5 on 2022-12-12 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0015_blocco_zavorra'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedario',
            name='addominali',
            field=models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedario',
            name='gambe',
            field=models.FloatField(default=25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedario',
            name='spinta',
            field=models.FloatField(default=0.025, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='schedario',
            name='tirata',
            field=models.FloatField(default=0.25, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
            preserve_default=False,
        ),
    ]
