# Generated by Django 2.1.5 on 2022-12-12 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0019_auto_20221212_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedario',
            name='addominali',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='schedario',
            name='gambe',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='schedario',
            name='spinta',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AlterField(
            model_name='schedario',
            name='tirata',
            field=models.IntegerField(default=0.0),
        ),
    ]
