# Generated by Django 2.1.5 on 2022-12-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0020_auto_20221212_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedario',
            name='abs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedario',
            name='legs',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedario',
            name='pull',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='schedario',
            name='push',
            field=models.IntegerField(default=0),
        ),
    ]
