# Generated by Django 2.1.5 on 2022-12-12 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0021_auto_20221212_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blocco',
            name='comment',
        ),
    ]
