# Generated by Django 2.1.5 on 2022-12-12 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0022_remove_blocco_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muscoli',
            name='esercizio_correlato',
        ),
        migrations.AddField(
            model_name='muscoli',
            name='esercizio',
            field=models.ManyToManyField(to='allenamento.Esercizio'),
        ),
    ]
