# Generated by Django 2.1.5 on 2022-12-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0029_auto_20221213_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='esercizio',
            name='time',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
