# Generated by Django 2.1.5 on 2022-12-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0030_esercizio_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='blocco',
            name='duration',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
