# Generated by Django 2.1.5 on 2022-12-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allenamento', '0031_blocco_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blocco',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
