# Generated by Django 2.1.5 on 2022-12-08 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('allenamento', '0004_muscoli'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiPiace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='allenamento.Schedario')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
